# NumPy进阶修炼80题
## 作者：刘早起
## 公众号：早起Python
未经授权严禁转载/引流等任何侵权行为，侵权必纠！

## 第一期｜热身20题:数据创建与访问

### 1.导入并查看NumPy版本

In [2]:
import numpy as np
print(np.__version__)

1.18.5


In [3]:
### 2.创建十个全为0的一维数组

In [4]:
np.zeros(10)

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [5]:
### 3.创建10个全为0的一维数据并修改数据类型为整数

In [6]:
np.zeros(10, dtype = 'int')

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

In [7]:
### 4.创建20个0-100固定步长的数

In [8]:
np.arange(0,100,5)

array([ 0,  5, 10, 15, 20, 25, 30, 35, 40, 45, 50, 55, 60, 65, 70, 75, 80,
       85, 90, 95])

In [9]:
### 5.从list创建数组

In [10]:
List = [1,2,3,4,5,6,7,8,9]
result = np.array(List)
result

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [11]:
### 6.创建一个三行三列全是1的矩阵

In [12]:
np.ones((3,3))

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [13]:
### 7.创建一个2行2列矩阵并且元素为布尔类型的True

In [14]:
np.full((2,2), True, dtype=bool)

array([[ True,  True],
       [ True,  True]])

In [15]:
### 8.创建等差数列
备注：从5开始，50结束，共10个数据

SyntaxError: invalid character in identifier (<ipython-input-15-dd49b3772c02>, line 2)

In [ ]:
np.linspace(start=5,stop=50,num=10)

In [ ]:
### 9.创建等差数列
备注：从5开始，50结束，共10个数据，数据类型为int32
思考：与上一题不同

In [ ]:
np.linspace(start=5,stop=50,num=10 , dtype='int32')

In [ ]:
np.arange(start = 5, stop = 55, step = 5,dtype = 'int32')

In [ ]:
### 10.创建3x3矩阵
备注：矩阵元素均为0—10之间的随机数

In [ ]:
np.random.randint(0,10,(3,3))

In [ ]:
### 11.创建3x3矩阵
备注：矩阵元素均为服从标准正态分布的随机数

In [ ]:
np.random.randn(3, 3)

In [ ]:
### 12.将第五题的result修改为3x3矩阵

In [ ]:
result = result.reshape(3,3)
result

In [ ]:
### 13.对上一题生成的result取转置

In [ ]:
result.T

In [ ]:
### 14.查看result的数据类型

In [ ]:
result.dtype

In [ ]:
### 15.查看result的内存占用

In [ ]:
#方法一：直接查看
print(result.nbytes)

In [ ]:
#方法2手动计算
print(result.itemsize *9)

In [ ]:
### 16.将result的数据类型修改为float

In [ ]:
result = result.astype(float)
result

In [ ]:
### 17.提取result第三行第三列的元素

In [ ]:
result[2,2]

In [ ]:
### 18.将result第三行第三列的元素放大十倍

In [ ]:
result[2,2] = result[2,2] * 10
result[2,2]

In [ ]:
### 19.提取result中的所有偶数

In [ ]:
result[result % 2 == 0]

In [ ]:
### 20.将result中所有奇数修改为666

In [ ]:
result[result % 2 == 1] = 666
result

In [ ]:
## NumPy进阶修炼80题 第二期 ｜基本矩阵操作与运算
## 公众号：早起Python

In [ ]:
### 21.创建主对角线都是5的5x5矩阵

In [ ]:
a = result.diag([5,5,5,5,5])
a

In [ ]:
### 22.交换第一列与第二列

In [ ]:
a = result[:, [1,0,2,3,4]]
a

In [ ]:
### 23.交换第一行与第二行

In [ ]:
b = result[[0,1,2,4,3], :]
b

In [ ]:
### 24.判断两个矩阵是否有任何元素不同(使用22,23两题得到的矩阵)


In [ ]:
print((a == b).all())

In [ ]:
### 25.计算两个矩阵不同元素的个数(使用22,23两题得到的矩阵)


In [ ]:
len(np.argwhere(a != b))

In [ ]:
### 26.找到两个矩阵不同元素的位置(使用22,23两题得到的矩阵)
np.argwhere(a != b)

In [ ]:
### 27.矩阵乘法(使用22,23两题得到的矩阵)
np.dot(a, b)

In [ ]:
### 28.矩阵对应元素相乘(使用22,23两题得到的矩阵)


In [ ]:
np.multiply(a,b)

In [ ]:
a * b

In [ ]:
### 29.计算行列式(使用21题生成的矩阵)

In [ ]:
np.linalg.det(result)

In [ ]:
### 30.矩阵求逆(使用21题生成的矩阵)

In [ ]:
np.linalg.inv(result)

In [ ]:
### 31.将22与23题生成的np.array对象修改为np.matrix对象


In [ ]:
a = np.matrix(a)
a

In [ ]:
b = np.matrix(b)
b

In [ ]:
### 32.计算上一题生成的两个np.matrix格式矩阵的对应元素乘积（对比异同）


In [ ]:
np.multiply(a,b)

In [ ]:
### 33.对31题生成的两个np.matrix格式矩阵做矩阵乘法（对比异同）
np.dot(a,b)

In [ ]:
### 34.将两个矩阵按照行拼接


In [ ]:
np.hstack((a,b))

In [ ]:
### 35.将两个矩阵按照列拼接
np.vstack((a,b))

In [ ]:
### 36.思考下面代码运行后new的结果


In [ ]:
new = np.pad(result,pad_width = 1,constant_values=1)
new

In [ ]:
### 37.找到new中大于1的元素的位置


In [ ]:
np.argwhere(new > 1)

In [ ]:
### 38.将new中大于1的元素修改为9


In [ ]:
new[new > 1] = 9
new

In [ ]:
### 39.对new按列求和


In [ ]:
np.sum(new, 0)

In [ ]:
### 40.对new按行求和


In [ ]:
np.sum(new, 1)

In [ ]:
np.sum(new)

In [ ]:
## NumPy进阶修炼第三期｜41-60
## 公众号：早起Python

In [ ]:
### 41 生成指定格式数据
备注：使用numpy生成6行6列的二维数组，值为1-100随机数

In [ ]:
import numpy as np
data = np.random.randint(1, 100, [6, 6])
data

In [ ]:
### 42 找到每列的最大值

In [ ]:
np.amax(data, axis=0)

In [ ]:
### 43 找到每行的最小值

In [ ]:
np.amin(data, axis=1)

In [ ]:
### 44 提取data每个元素的出现次数

In [ ]:
#去除數組中的重複數字，並進行排序之後輸出
np.unique(data,return_counts=True)

In [ ]:
### 45 获取data每行元素的大小排名

In [ ]:
np.argsort()
功能: 將矩陣a按照axis排序，並返回排序後的下標(位置)
引數: a:輸入矩陣， axis:需要排序的維度
返回值: 輸出排序後的下標(位置)

In [ ]:
data.argsort(axis=0)

In [ ]:
data.argsort(axis=-1)

In [ ]:
### 46 将数组按行重复一次

In [ ]:
np.repeat(data, 2, axis=0)

In [ ]:
### 47 去除数组的重复行

In [ ]:
np.unique(data,axis = 0)

In [ ]:
### 48 不放回抽样
备注：从data的第一行中不放回抽3个元素

In [ ]:
np.random.choice(data[0:1][0], 3, replace=False)

In [ ]:
np.random.choice(data[0:1][0], 6, replace=0) #不放回

In [ ]:
np.random.choice(data[0:1][0], 6, replace=1) #放回

In [ ]:
### 49 提取data第二行中不含第三行的元素的元素

In [ ]:
a = data[1:2]
b = data[2:3]
index=np.isin(a,b)
array=a[~index]
array

In [ ]:
index

In [ ]:
a

In [ ]:
b

In [ ]:
### 50 判断data是否有空行

In [ ]:
(~data.any(axis=1)).any()

In [ ]:
(data.any(axis=1)).any()

In [ ]:
### 51 将每行升序排列

In [1]:
data.sort(axis = 1)
data

NameError: name 'data' is not defined

In [ ]:
### 52 将data的数据格式修改为float

In [ ]:
### 53 将小于5的元素修改为nan

In [ ]:
### 54 删除data1含有nan的行

In [ ]:
### 55 找出data1第一行出现频率最高的值

In [ ]:
### 56 找到data1中与100最接近的数字

In [ ]:
### 57 data1每一行的元素减去每一行的平均值

In [ ]:
### 58 将data1归一化至区间[0,1]

In [ ]:
### 59  将data1标准化

In [ ]:
### 60 将data1存储至本地

In [ ]:
## NumPy进阶修炼第四期｜NumPy最后二十问
## 公众号：早起Python

In [1]:
import numpy as np
import pandas as pd
import warnings
warnings.filterwarnings("ignore")

In [ ]:
### 61.如何获得两个数组之间的相同元素
输入:

arr1 = np.random.randint(10,6,6)

arr2 = np.random.randint(10,6,6)

In [23]:
print("arr1: %s"%arr1)
print("arr2: %s"%arr2)
np.intersect1d(arr1,arr2)

arr1: [9 4 1 4 9 9 8 5 3 1]
arr2: [1 5 8 7 9 2 6 9 1 2]


array([1, 5, 8, 9])

In [ ]:
### 62.如何从一个数组中删除另一个数组存在的元素
输入:

arr1 = np.random.randint(1,10,10)

arr2 = np.random.randint(1,10,10)

In [ ]:
### 63.如何修改一个数组为只读模式
输入:

arr1 = np.random.randint(1,10,10)

In [ ]:
### 64.如何将list转为numpy数组
输入:

a = [1,2,3,4,5]

In [ ]:
### 65.如何将pd.DataFrame转为numpy数组
输入:

df = pd.DataFrame({'A':[1,2,3],'B':[4,5,6],'C':[7,8,9]})

In [ ]:
### 66.如何使用numpy进行描述性统计分析
输入：

arr1 = np.random.randint(1,10,10)

arr2 = np.random.randint(1,10,10)

In [ ]:
### 67.如何使用numpy进行概率抽样
输入：

arr = np.array([1,2,3,4,5])

In [ ]:
### 68.如何创建副本
输入：

arr = np.array([1,2,3,4,5])

In [ ]:
### 69.如何对数组切片
输入:
arr = np.arange(10)

备注：从索引2开始到索引8停止，间隔为2

In [ ]:
### 70.如何使用NumPy操作字符串
输入:

str1 = ['I love']

str2 = [' Python']

In [ ]:
### 71.如何对数据向上/下取整
输入:

arr = np.random.uniform(0,10,10)

In [ ]:
### 72.如何取消默认科学计数显示数据

In [ ]:
### 73.如何使用NumPy对二维数组逆序
输入：

arr = np.random.randint(1,10,[3,3])

In [ ]:
### 74.如何使用NumPy根据位置查找元素
输入：

arr1 = np.random.randint(1,10,5)

arr2 = np.random.randint(1,20,10)

备注：在arr2中根据arr1中元素以位置查找

In [ ]:
### 75.如何使用numpy求余数
输入：

a = 10

b = 3

In [ ]:
### 76.如何使用NumPy进行矩阵SVD分解
输入：

A = np.random.randint(1,10,[3,3])

In [ ]:
### 77.如何使用NumPy多条件筛选数据
输入：

arr = np.random.randint(1,20,10)

In [ ]:
### 78.如何使用NumPy对数组分类
输入：

arr = np.random.randint(1,20,10)

备注：将大于等于7，或小于3的元素标记为1，其余为0

In [ ]:
### 79如何使用NumPy压缩矩阵
输入：

arr = np.random.randint(1,10,[3,1])

备注：从数组的形状中删除单维度条目，即把shape中为1的维度去掉

In [ ]:
### 80.如何使用numpy求解线性方程组
输入：

A = np.array([[1, 2, 3], [2, -1, 1], [3, 0, -1]])

b = np.array([9, 8, 3])

求解Ax = b