In [1]:
from sklearn.ensemble import RandomForestRegressor
import pandas as pd 
import numpy as np
from pandas import Series,DataFrame

data_train = pd.read_csv(r"C:\Users\11004076\Downloads\train.csv")
df = pd.DataFrame(data_train)

In [2]:
df

PassengerId  Survived  Pclass  \
0              1         0       3   
1              2         1       1   
2              3         1       3   
3              4         1       1   
4              5         0       3   
..           ...       ...     ...   
886          887         0       2   
887          888         1       1   
888          889         0       3   
889          890         1       1   
890          891         0       3   

                                                  Name  Sex   Age  SibSp  \
0                              Braund, Mr. Owen Harris    1  22.0      1   
1    Cumings, Mrs. John Bradley (Florence Briggs Th...    0  38.0      1   
2                               Heikkinen, Miss. Laina    0  26.0      0   
3         Futrelle, Mrs. Jacques Heath (Lily May Peel)    0  35.0      1   
4                             Allen, Mr. William Henry    1  35.0      0   
..                                                 ...  ...   ...    ...   
886                              Montvila, Rev. Juozas    1  27.0      0   
887                       Graham, Miss. Margaret Edith    0  19.0      0   
888           Johnston, Miss. Catherine Helen "Carrie"    0   NaN      1   
889                              Behr, Mr. Karl Howell    1  26.0      0   
890                                Dooley, Mr. Patrick    1  32.0      0   

     Parch            Ticket     Fare Cabin Embarked  
0        0         A/5 21171   7.2500   NaN        S  
1        0          PC 17599  71.2833   C85        C  
2        0  STON/O2. 3101282   7.9250   NaN        S  
3        0            113803  53.1000  C123        S  
4        0            373450   8.0500   NaN        S  
..     ...               ...      ...   ...      ...  
886      0            211536  13.0000   NaN        S  
887      0            112053  30.0000   B42        S  
888      2        W./C. 6607  23.4500   NaN        S  
889      0            111369  30.0000  C148        C  
890      0            370376   7.7500   NaN        Q  

[891 rows x 12 columns]

In [2]:
age_df = df[['Age','Fare', 'Parch', 'SibSp', 'Pclass']]
age_df

Age     Fare  Parch  SibSp  Pclass
0    22.0   7.2500      0      1       3
1    38.0  71.2833      0      1       1
2    26.0   7.9250      0      0       3
3    35.0  53.1000      0      1       1
4    35.0   8.0500      0      0       3
..    ...      ...    ...    ...     ...
886  27.0  13.0000      0      0       2
887  19.0  30.0000      0      0       1
888   NaN  23.4500      2      1       3
889  26.0  30.0000      0      0       1
890  32.0   7.7500      0      0       3

[891 rows x 5 columns]

In [5]:
known_age = age_df[age_df.Age.notnull()].iloc[:,:].values
unknown_age = age_df[age_df.Age.isnull()].iloc[:,:].values

In [4]:
known_age

array([[22.    ,  7.25  ,  0.    ,  1.    ,  3.    ],
       [38.    , 71.2833,  0.    ,  1.    ,  1.    ],
       [26.    ,  7.925 ,  0.    ,  0.    ,  3.    ],
       ...,
       [19.    , 30.    ,  0.    ,  0.    ,  1.    ],
       [26.    , 30.    ,  0.    ,  0.    ,  1.    ],
       [32.    ,  7.75  ,  0.    ,  0.    ,  3.    ]])

In [6]:
unknown_age

array([[     nan,   8.4583,   0.    ,   0.    ,   3.    ],
       [     nan,  13.    ,   0.    ,   0.    ,   2.    ],
       [     nan,   7.225 ,   0.    ,   0.    ,   3.    ],
       [     nan,   7.225 ,   0.    ,   0.    ,   3.    ],
       [     nan,   7.8792,   0.    ,   0.    ,   3.    ],
       [     nan,   7.8958,   0.    ,   0.    ,   3.    ],
       [     nan, 146.5208,   0.    ,   1.    ,   1.    ],
       [     nan,   7.75  ,   0.    ,   0.    ,   3.    ],
       [     nan,   7.2292,   0.    ,   0.    ,   3.    ],
       [     nan,   7.8958,   0.    ,   0.    ,   3.    ],
       [     nan,   8.05  ,   0.    ,   0.    ,   3.    ],
       [     nan,  15.5   ,   0.    ,   1.    ,   3.    ],
       [     nan,   7.75  ,   0.    ,   0.    ,   3.    ],
       [     nan,  21.6792,   0.    ,   2.    ,   3.    ],
       [     nan,  35.5   ,   0.    ,   0.    ,   1.    ],
       [     nan,  27.7208,   0.    ,   0.    ,   1.    ],
       [     nan,  15.2458,   1.    ,   1.    ,   3.    

In [7]:
y = known_age[:, 0]
y

array([22.  , 38.  , 26.  , 35.  , 35.  , 54.  ,  2.  , 27.  , 14.  ,
        4.  , 58.  , 20.  , 39.  , 14.  , 55.  ,  2.  , 31.  , 35.  ,
       34.  , 15.  , 28.  ,  8.  , 38.  , 19.  , 40.  , 66.  , 28.  ,
       42.  , 21.  , 18.  , 14.  , 40.  , 27.  ,  3.  , 19.  , 18.  ,
        7.  , 21.  , 49.  , 29.  , 65.  , 21.  , 28.5 ,  5.  , 11.  ,
       22.  , 38.  , 45.  ,  4.  , 29.  , 19.  , 17.  , 26.  , 32.  ,
       16.  , 21.  , 26.  , 32.  , 25.  ,  0.83, 30.  , 22.  , 29.  ,
       28.  , 17.  , 33.  , 16.  , 23.  , 24.  , 29.  , 20.  , 46.  ,
       26.  , 59.  , 71.  , 23.  , 34.  , 34.  , 28.  , 21.  , 33.  ,
       37.  , 28.  , 21.  , 38.  , 47.  , 14.5 , 22.  , 20.  , 17.  ,
       21.  , 70.5 , 29.  , 24.  ,  2.  , 21.  , 32.5 , 32.5 , 54.  ,
       12.  , 24.  , 45.  , 33.  , 20.  , 47.  , 29.  , 25.  , 23.  ,
       19.  , 37.  , 16.  , 24.  , 22.  , 24.  , 19.  , 18.  , 19.  ,
       27.  ,  9.  , 36.5 , 42.  , 51.  , 22.  , 55.5 , 40.5 , 51.  ,
       16.  , 30.  ,

In [8]:
X = known_age[:, 1:]
X

array([[ 7.25  ,  0.    ,  1.    ,  3.    ],
       [71.2833,  0.    ,  1.    ,  1.    ],
       [ 7.925 ,  0.    ,  0.    ,  3.    ],
       ...,
       [30.    ,  0.    ,  0.    ,  1.    ],
       [30.    ,  0.    ,  0.    ,  1.    ],
       [ 7.75  ,  0.    ,  0.    ,  3.    ]])

In [9]:
# fit到RandomForestRegressor之中
rfr = RandomForestRegressor(random_state=0, n_estimators=2000, n_jobs=-1)
rfr.fit(X, y)

RandomForestRegressor(bootstrap=True, ccp_alpha=0.0, criterion='mse',
                      max_depth=None, max_features='auto', max_leaf_nodes=None,
                      max_samples=None, min_impurity_decrease=0.0,
                      min_impurity_split=None, min_samples_leaf=1,
                      min_samples_split=2, min_weight_fraction_leaf=0.0,
                      n_estimators=2000, n_jobs=-1, oob_score=False,
                      random_state=0, verbose=0, warm_start=False)

In [12]:
# 用得到的模型进行未知年龄结果预测
predictedAges = rfr.predict(unknown_age[:, 1::])
predictedAges

array([23.83895259, 32.06649305, 29.51820514, 29.51820514, 22.38011324,
       27.94720616, 36.10804822, 35.2958243 , 22.87630686, 27.94720616,
       30.70572678, 33.12898535, 35.2958243 , 23.45968333, 44.06483036,
       41.20008848, 17.09991595, 27.94720616, 30.70572678, 23.32262739,
       30.70572678, 30.70572678, 27.94720616, 27.51545426, 33.55117591,
       30.70572678, 35.2958243 , 25.78337698, 25.34409583, 29.78279613,
       25.52340334, 10.86986696, 26.03188214, 49.5542756 ,  7.30954704,
       10.86986696, 31.71894048, 46.24976824, 33.12898535, 35.2958243 ,
       35.2958243 , 10.86986696, 31.09342985, 27.94720616,  7.30954704,
       31.10838452, 20.80015413, 33.12898535, 29.78279613, 34.62028571,
       35.2958243 , 35.2958243 , 36.87489821, 35.2958243 , 35.05181757,
       57.74249226, 41.20008848, 41.57487718, 35.2958243 , 23.31368333,
       42.57451554, 30.70572678, 28.57888393, 10.86986696, 23.31368333,
       31.42587794, 27.94720616, 26.68916849, 59.96916448, 29.51

In [13]:
df.Age.isnull()

0      False
1      False
2      False
3      False
4      False
       ...  
886    False
887    False
888     True
889    False
890    False
Name: Age, Length: 891, dtype: bool

In [14]:
df.loc[ (df.Age.isnull()), 'Age' ]

5     NaN
17    NaN
19    NaN
26    NaN
28    NaN
       ..
859   NaN
863   NaN
868   NaN
878   NaN
888   NaN
Name: Age, Length: 177, dtype: float64

In [15]:
# 用得到的预测结果填补原缺失数据
df.loc[ (df.Age.isnull()), 'Age' ] = predictedAges 

In [16]:
df

PassengerId  Survived  Pclass  \
0              1         0       3   
1              2         1       1   
2              3         1       3   
3              4         1       1   
4              5         0       3   
..           ...       ...     ...   
886          887         0       2   
887          888         1       1   
888          889         0       3   
889          890         1       1   
890          891         0       3   

                                                  Name  Sex       Age  SibSp  \
0                              Braund, Mr. Owen Harris    1  22.00000      1   
1    Cumings, Mrs. John Bradley (Florence Briggs Th...    0  38.00000      1   
2                               Heikkinen, Miss. Laina    0  26.00000      0   
3         Futrelle, Mrs. Jacques Heath (Lily May Peel)    0  35.00000      1   
4                             Allen, Mr. William Henry    1  35.00000      0   
..                                                 ...  ...       ...    ...   
886                              Montvila, Rev. Juozas    1  27.00000      0   
887                       Graham, Miss. Margaret Edith    0  19.00000      0   
888           Johnston, Miss. Catherine Helen "Carrie"    0  16.19395      1   
889                              Behr, Mr. Karl Howell    1  26.00000      0   
890                                Dooley, Mr. Patrick    1  32.00000      0   

     Parch            Ticket     Fare Cabin Embarked  
0        0         A/5 21171   7.2500   NaN        S  
1        0          PC 17599  71.2833   C85        C  
2        0  STON/O2. 3101282   7.9250   NaN        S  
3        0            113803  53.1000  C123        S  
4        0            373450   8.0500   NaN        S  
..     ...               ...      ...   ...      ...  
886      0            211536  13.0000   NaN        S  
887      0            112053  30.0000   B42        S  
888      2        W./C. 6607  23.4500   NaN        S  
889      0            111369  30.0000  C148        C  
890      0            370376   7.7500   NaN        Q  

[891 rows x 12 columns]

In [25]:
from sklearn.ensemble import RandomForestRegressor
import pandas as pd #数据分析
import numpy as np #科学计算
from pandas import Series,DataFrame

train = pd.read_csv(r"C:\Users\11004076\Downloads\train.csv")
df = pd.DataFrame(train)


### 使用 RandomForestClassifier 填补缺失的年龄属性
def set_missing_ages(df):
    
    # 把已有的数值型特征取出来丢进Random Forest Regressor中
    age_df = df[['Age','Fare', 'Parch', 'SibSp', 'Pclass']]

    # 乘客分成已知年龄和未知年龄两部分
    known_age = age_df[age_df.Age.notnull()].as_matrix() #篩選有年齡的成矩陣
    unknown_age = age_df[age_df.Age.isnull()].as_matrix() #篩選無年齡的成矩陣

    # y即目标年龄
    y = known_age[:, 0] #矩陣的第0欄

    # X即特征属性值
    X = known_age[:, 1:] #矩陣的第1~最後欄

    # fit到RandomForestRegressor之中
    rfr = RandomForestRegressor(random_state=0, n_estimators=2000, n_jobs=-1)
    rfr.fit(X, y)
    
    # 用得到的模型进行未知年龄结果预测
    predictedAges = rfr.predict(unknown_age[:, 1::])
    
    # 用得到的预测结果填补原缺失数据
    df.loc[ (df.Age.isnull()), 'Age' ] = predictedAges 
    
    return df, rfr

#Cabin遺失太多，所以直接分有無
def set_Cabin_type(df):
    df.loc[ (df.Cabin.notnull()), 'Cabin' ] = "Yes"
    df.loc[ (df.Cabin.isnull()), 'Cabin' ] = "No"
    return df

train, rfr = set_missing_ages(train)


C:\Users\11004076\Anaconda3\lib\site-packages\ipykernel_launcher.py:17: FutureWarning: Method .as_matrix will be removed in a future version. Use .values instead.
C:\Users\11004076\Anaconda3\lib\site-packages\ipykernel_launcher.py:18: FutureWarning: Method .as_matrix will be removed in a future version. Use .values instead.


In [31]:
rfr

RandomForestRegressor(bootstrap=True, ccp_alpha=0.0, criterion='mse',
                      max_depth=None, max_features='auto', max_leaf_nodes=None,
                      max_samples=None, min_impurity_decrease=0.0,
                      min_impurity_split=None, min_samples_leaf=1,
                      min_samples_split=2, min_weight_fraction_leaf=0.0,
                      n_estimators=2000, n_jobs=-1, oob_score=False,
                      random_state=0, verbose=0, warm_start=False)

In [26]:
train.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 891 entries, 0 to 890
Data columns (total 12 columns):
PassengerId    891 non-null int64
Survived       891 non-null int64
Pclass         891 non-null int64
Name           891 non-null object
Sex            891 non-null int64
Age            891 non-null float64
SibSp          891 non-null int64
Parch          891 non-null int64
Ticket         891 non-null object
Fare           891 non-null float64
Cabin          204 non-null object
Embarked       889 non-null object
dtypes: float64(2), int64(6), object(4)
memory usage: 83.7+ KB


In [29]:
train = set_Cabin_type(train)

In [30]:
train.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 891 entries, 0 to 890
Data columns (total 12 columns):
PassengerId    891 non-null int64
Survived       891 non-null int64
Pclass         891 non-null int64
Name           891 non-null object
Sex            891 non-null int64
Age            891 non-null float64
SibSp          891 non-null int64
Parch          891 non-null int64
Ticket         891 non-null object
Fare           891 non-null float64
Cabin          891 non-null object
Embarked       889 non-null object
dtypes: float64(2), int64(6), object(4)
memory usage: 83.7+ KB
