In [ ]:
合併&加入資料(列表、字典、數組)
https://www.twblogs.net/a/5c4ae704bd9eee6e7e06adcb?lang=zh-cn

# 一、合併List

### extend(x)：擴展
* 擴展(extend)元素x後，把它們通通加到串列(list)裡
* 也就是先將x展開來(可以想成list的[ ]會被拆開)，再一個一個放入最後的位置
* ex:將塑膠袋打開後，將裡面的剪刀、眼鏡、牛奶，依序放入綠色抽屜櫃的櫃子裡，總共會放入三格櫃子

In [22]:
#一般List
a = [1,2,3,4,5]
b = ['A','B','C','D'] #拆開[]，再一個個依序放入a末位
a.extend(b)
print(a)

#在DataFrame中的型態
import pandas as pd
df = pd.DataFrame(a)
df

[1, 2, 3, 4, 5, 'A', 'B', 'C', 'D']


0
0  1
1  2
2  3
3  4
4  5
5  A
6  B
7  C
8  D

In [29]:
#巢狀List
a = [[1,2,3,4,5]]
b = [['A','B','C','D']] #拆開[]，還是list，再將一個list放入a末位
a.extend(b)
print(a)

#在DataFrame中的型態
import pandas as pd
df = pd.DataFrame(a)
df

[[1, 2, 3, 4, 5], ['A', 'B', 'C', 'D']]


0  1  2  3    4
0  1  2  3  4  5.0
1  A  B  C  D  NaN

### append(x)：加入
* 加入(append)一個元素x到串列(list)裡
* 向列表尾部追加一個新元素，新元素只佔一個索引位
* ex:直接將一整個塑膠袋(內含剪刀、眼鏡、牛奶)放入綠色抽屜櫃的一格櫃子裡

In [30]:
#一般List
a = [1,2,3,4,5]
b = ['A','B','C','D'] #直接將b list放入a的末位
a.append(b)
print(a)

#在DataFrame中的型態
import pandas as pd
df = pd.DataFrame(a)
df

[1, 2, 3, 4, 5, ['A', 'B', 'C', 'D']]


0
0             1
1             2
2             3
3             4
4             5
5  [A, B, C, D]

In [26]:
#巢狀List
a = [[1,2,3,4,5]]
b = ['A','B','C','D'] #直接將b list放入a的末位
a.append(b)
print(a)

#在DataFrame中的型態
import pandas as pd
df = pd.DataFrame(a)
df

[[1, 2, 3, 4, 5], ['A', 'B', 'C', 'D']]


0  1  2  3    4
0  1  2  3  4  5.0
1  A  B  C  D  NaN

### a+b：
* 看上去和extend()一樣，但是需要生成了一個新的列表存兩個列表的和
* 需要消耗額外的內存，特別是當list較大時，盡量不要使用“+”來添加list

In [7]:
a = [1,2,3,4,5]
b = ['A','B','C','D']
c = a+b
print(c)

[1, 2, 3, 4, 5, 'A', 'B', 'C', 'D']


### a+=b：
效果和extend()一樣，也是在原有列表上增加

### insert():
將一個元素插入到列表中，但其參數有兩個（如insert(1,”g”)），第一個參數是索引點，即插入的位置，第二個參數是插入的元素。

In [15]:
list1 = ['a', 'b', 'c', 'd']
list1.insert(1,'x')
list1

['a', 'x', 'b', 'c', 'd']

In [31]:
list1 = ['a', 'b', 'c', 'd']
list1.insert(1,[1,2])
list1

['a', [1, 2], 'b', 'c', 'd']

In [60]:
a = [1,2,3,4,5]
b = ['A','B','C','D']
a+=b
a

[1, 2, 3, 4, 5, 'A', 'B', 'C', 'D']

### 切片，a[0:0]

In [69]:
a = [1,2,3,4,5]
print(a[0:0])
print(a[0:1])
print(a[0:2] , "------")
print(a[0])
print(a[1])
print(a[2])

[]
[1]
[1, 2] ------
1
2
3


In [12]:
a = [1,2,3,4,5]
b = ['A','B','C','D']
a[0:0] = b  #在 1的前面加入b
print(a)

['A', 'B', 'C', 'D', 1, 2, 3, 4, 5]


In [70]:
a = [1,2,3,4,5]
b = ['A','B','C','D']
a[1:0] = b  #在 1和2之間加入b
print(a)

[1, 'A', 'B', 'C', 'D', 2, 3, 4, 5]


In [14]:
a = [1,2,3,4,5]
b = ['A','B','C','D']
a[1:1] = b  #在 1和2之間加入b
print(a)

[1, 'A', 'B', 'C', 'D', 2, 3, 4, 5]


In [15]:
a = [1,2,3,4,5]
b = ['A','B','C','D']
a[2] = b #在原本3的位子改為b
print(a)

[1, 2, ['A', 'B', 'C', 'D'], 4, 5]


# 二、合併Dict

### 將index相同的行放到同一列

In [1]:
from collections import defaultdict

data = [['a', 1],['a', 3],['b',1],['b',2],['c',1],['c', 5]]
dict_data = defaultdict(set)
for line in data:
    if len(line) > 1:
        dict_data[line[0]].update(line[1:])
print(dict_data)

defaultdict(<class 'set'>, {'a': {1, 3}, 'b': {1, 2}, 'c': {1, 5}})


### dict(a,**b)
b會覆蓋a中key相同的value，結果是所有不同key的value, python 2 不支持，python3.5及以上支持

In [16]:
#适用于所有key值不同的dict
a = {'age':17, 'name':'Mary', 'gender':'female'}
b = {'age':19, 'name':'Joe','grade':90,'class':'Two'}
c = dict(a, **b)
print(c)

{'age': 19, 'name': 'Joe', 'gender': 'female', 'grade': 90, 'class': 'Two'}


### dict(a.items()+b.items()) 
python3不支持

In [16]:
#仅适用于python2
a = {'age':17, 'name':'Mary', 'gender':'female'}
b = {'age':19, 'name':'Joe','grade':90,'class':'Two'}
c = dict(a.items()+b.items())
print(c)

TypeError: unsupported operand type(s) for +: 'dict_items' and 'dict_items'

### update（）

In [19]:
a.update(b)
print(a)
#或者,不改变a
c = {}
c.update(a)#或者 c = a.copy()
c.update(b)
print(c)

{'age': 19, 'name': 'Joe', 'gender': 'female', 'grade': 90, 'class': 'Two'}
{'age': 19, 'name': 'Joe', 'gender': 'female', 'grade': 90, 'class': 'Two'}


### 字典的常規處理方法

In [20]:
for k, v in a.items():
    c[k] = v
print(c)
for k, v in b.items():
    c[k] = v
print(c)

{'age': 19, 'name': 'Joe', 'gender': 'female', 'grade': 90, 'class': 'Two'}
{'age': 19, 'name': 'Joe', 'gender': 'female', 'grade': 90, 'class': 'Two'}


# 三、合併數組，numpy庫

### np.vstack()：橫向按行、hstack()：縱向按列

In [21]:
import numpy as np
a = [[1,2,3],[4,5,6]]#列表和数组类型都适用
b = [[7,8,9],[3,3,3]]
c = np.vstack((a,b))
print(c)  #输出，类型是数组型

[[1 2 3]
 [4 5 6]
 [7 8 9]
 [3 3 3]]


In [24]:
c = np.hstack((a,b))
print(c)

[[1 2 3 7 8 9]
 [4 5 6 3 3 3]]


### np.r_[ ]：橫向按行、np.c_[ ]：縱向按列

In [22]:
c = np.r_[a,b]
print(c) #输出,类型是数组型

[[1 2 3]
 [4 5 6]
 [7 8 9]
 [3 3 3]]


In [25]:
c = np.c_[a,b]
print(c)
#输出，类型是数组型

[[1 2 3 7 8 9]
 [4 5 6 3 3 3]]


### concatenate()

In [23]:
# axis = 0：橫向按行
c = np.concatenate([a,b],axis = 0)
print(c)

[[1 2 3]
 [4 5 6]
 [7 8 9]
 [3 3 3]]


In [26]:
# axis = 1：縱向按列
c = np.concatenate([a,b],axis = 1)
print(c)

[[1 2 3 7 8 9]
 [4 5 6 3 3 3]]


# 四、合併數組，pandas庫

In [23]:
import pandas as pd
left = pd.DataFrame([['a', 1], ['b', 2]], list('XY'), list('AB'))
left

A  B
X  a  1
Y  b  2

In [24]:
right = pd.DataFrame([['a', 3], ['b', 4]], list('XY'), list('AC'))
right

A  C
X  a  3
Y  b  4

## join函數：
根據索引合併

In [25]:
left.join(right, lsuffix='_')
#請注意，索引已保留，我們有4列。從2列left ，和2個right 。

A_  B  A  C
X  a  1  a  3
Y  b  2  b  4

In [30]:
right.reset_index()

index  A  C
0     X  a  3
1     Y  b  4

In [32]:
#如果索引沒有對齊
left.join(right.reset_index(), lsuffix='_', how='outer')


A_    B index    A    C
X    a  1.0   NaN  NaN  NaN
Y    b  2.0   NaN  NaN  NaN
0  NaN  NaN     X    a  3.0
1  NaN  NaN     Y    b  4.0

In [27]:
#我使用外連接來更好地說明這一點。如果索引不對齊，則結果將是索引的並集。
#我們可以告訴join使用左側數據框中的特定列作為連接鍵，但它仍將使用右側的索引。

left.reset_index().join(right, on='index', lsuffix='_')

index A_  B  A  C
0     X  a  1  a  3
1     Y  b  2  b  4

## merge函數：
預設合併重疊列、或是指定特定列用參數on合併

In [28]:
left.merge(right)

A  B  C
0  a  1  3
1  b  2  4

In [ ]:
注意索引是[0, 1]而不再是['X', 'Y']
也可以使用left_index或right_index參數明確指定要合併索引
這看起來與上面的join示例完全相同。

In [29]:
left.merge(right, left_index=True, right_index=True, suffixes=['_', ''])

A_  B  A  C
X  a  1  a  3
Y  b  2  b  4

### merge範例

In [ ]:
參數	描述
left	參與合併的左側DataFrame
right	參與合併的右側DataFrame
how	連接方式：inner,默認；outer,left,right
on	連接的列名，和sql連接的on類似
left_on	左側DF用作連接的鍵
right_on	右側DF用作連接的鍵
left_index	將左側的行索引用作其連接鍵
right_on	將右側的行索引用作其連接鍵
sort	根據連接鍵對合併後的數據進行排序，默認True; 類似sql的order by
suffixes	字符串值元組，用於追加重疊列名的末尾，重疊列名重命名
copy	設置False，可以在某些特殊情況下避免將數據複製到結果數據結構中

In [30]:
import pandas as pd 
import numpy as np
df1 = pd.DataFrame({'key':['d','d','a','c'], 'data1':range(4)})
df1

key  data1
0   d      0
1   d      1
2   a      2
3   c      3

In [31]:
df2 = pd.DataFrame({'key':['a','b','c'], 'data2':range(3)})
df2

key  data2
0   a      0
1   b      1
2   c      2

In [32]:
#(1) 默認合併，key相同合併data
df3 = pd.merge(df1,df2)#等同于df1.merge(df2)
df3

key  data1  data2
0   a      2      0
1   c      3      2

In [33]:
#（2）內連接，取交集
df3 = df1.merge(df2,on = 'key', how = 'inner')
df3

key  data1  data2
0   a      2      0
1   c      3      2

In [34]:
#(3)外連接，取並集，並有NaN填充
df3 = df1.merge(df2, on = 'key', how = 'outer')
df3

key  data1  data2
0   d    0.0    NaN
1   d    1.0    NaN
2   a    2.0    0.0
3   c    3.0    2.0
4   b    NaN    1.0

In [35]:
#(4)左側DataFrame(df1)取全部，右側DataFrame(df2)取部分
df3 = df1.merge(df2, on = 'key', how = 'left')
df3

key  data1  data2
0   d      0    NaN
1   d      1    NaN
2   a      2    0.0
3   c      3    2.0

In [36]:
#(5)右側DataFrame(df2)取全部，左側DataFrame(df1)取部分
df3 = df1.merge(df2, on = 'key', how = 'right')
df3

key  data1  data2
0   a    2.0      0
1   c    3.0      2
2   b    NaN      1

In [37]:
#(6)如果左右側DataFrame的連接鍵列名不一致，但是取值有重疊，可使用left_on、right_on來指定左右連接鍵
df3 = pd.DataFrame({'lkey':['b','b','a','c','a','a','b'],'data1': range(7)})
df4 = pd.DataFrame({'rkey':['a','b','d'],'data2':range(3)})
df3.merge(df4,left_on = 'lkey',right_on = 'rkey',how = 'inner')

lkey  data1 rkey  data2
0    b      0    b      1
1    b      1    b      1
2    b      6    b      1
3    a      2    a      0
4    a      4    a      0
5    a      5    a      0

In [ ]:
### 3.4.2 索引合併
當連接鍵位於索引中時，成為索引上的合併，可以通過merge函數，傳入left_index、right_index來說明應該被索引的情況

In [39]:
left1 = pd.DataFrame({'key':['a','b','a','a','b','c'],'value': range(6)})
right1 = pd.DataFrame({'group_val':[3.5, 7]},index = ['a','b'])
df = pd.merge(left1,right1,left_on = 'key',right_index = True)
df

key  value  group_val
0   a      0        3.5
2   a      2        3.5
3   a      3        3.5
1   b      1        7.0
4   b      4        7.0

## concat函數：
軸向連接

In [ ]:
參數	描述
objs	對象（列表或字典），對象的數據類型是pandas，不可為空
axis	連接的軸，0是縱軸（行），1是橫軸（列）
join	合併的方式，inner,outer（默認）
ignore	不保留連接軸上的索引，產生一組新的索引

In [40]:
s1 = pd.Series([0,1,2],index = ['a','b','c'])
s2 = pd.Series([2,3,4],index = ['c','f','e'])
s3 = pd.Series([4,5,6],index = ['c','f','g'])

In [42]:
#(1)默認情況，連集，縱向連接
s4 = pd.concat([s1, s2, s3])
s4

a    0
b    1
c    2
c    2
f    3
e    4
c    4
f    5
g    6
dtype: int64

In [43]:
s4 = pd.concat([s1, s2, s3],ignore_index = True)
s4

0    0
1    1
2    2
3    2
4    3
5    4
6    4
7    5
8    6
dtype: int64

In [44]:
#(2)縱向取交集,注意該方法對對象表中有重複索引時失效
s4 = pd.concat([s1,s2,s3],axis = 1,join = 'inner')
s4

0  1  2
c  2  2  4

In [45]:
#(3)橫向索引取聯集，縱向索引取交集,注意該方法對對象表中有重複索引時失效
s4 = pd.concat([s1,s2,s3],axis = 1,join = 'outer')
s4

C:\Users\11004076\Anaconda3\lib\site-packages\ipykernel_launcher.py:1: FutureWarning: Sorting because non-concatenation axis is not aligned. A future version
of pandas will change to not sort by default.

To accept the future behavior, pass 'sort=False'.

To retain the current behavior and silence the warning, pass 'sort=True'.

  """Entry point for launching an IPython kernel.


0    1    2
a  0.0  NaN  NaN
b  1.0  NaN  NaN
c  2.0  2.0  4.0
e  NaN  4.0  NaN
f  NaN  3.0  5.0
g  NaN  NaN  6.0

## combine_first函數：
重疊索引時填補缺失值

In [46]:
a = pd.Series([np.nan,2.5,np.nan,3.5,4.5,np.nan],index = ['a','b','c','d','e','f'])
a

a    NaN
b    2.5
c    NaN
d    3.5
e    4.5
f    NaN
dtype: float64

In [47]:
b = pd.Series(np.arange(len(a)),index = ['a','b','c','d','e','f'])
b

a    0
b    1
c    2
d    3
e    4
f    5
dtype: int32

In [48]:
#用b填补a的空白
a.combine_first(b)

a    0.0
b    2.5
c    2.0
d    3.5
e    4.5
f    5.0
dtype: float64